### PR TITLE
New :on-request handler

### PR DESCRIPTION
**Pull request by kennethkalmer**
Allow dispatchers to keep track of raw xhrio objects, as per #3

### CODE REVIEW

**Comment by kennethkalmer** [comment]
I just took a stab at this as mental exercise. I'm busy wiring this up in a real life app to see how it performs in both cases mentioned in #3 (debouncing duplicate requests and cancelling long/slow requests)

**Comment by kennethkalmer** [comment]
As with all things non-deterministic, this is tricky. That said, my first refactorings for both cases held up quite nicely. Although it is more verbose than it was, it is very clear and has the same shape as all the other handlers in the app. Being able to place the requests in the `app-db` and later recall it to cancel is quite neat.

Wondering if @deepxg & @flexsurfer have any thoughts on if this implementation could solve their needs?

**Comment by kennethkalmer** [comment]
👋 

Any feedback on this PR?

**Comment by Frozenlock** [comment]
As noted in [cljs-ajax changelogs](https://github.com/JulianBirch/cljs-ajax/blob/master/CHANGES.md#version-07):

>It is intended that the default implementation for JavaScript uses XmlHttpRequest directly and XhrIO is deprecated in 0.8. Be warned.

**Comment by kennethkalmer** [comment]
Any chance of getting this merged, or is there possibly an alternative strategy that we could use to stop relying on a fork of a great project?

I should have done a better job earlier to address @Frozenlock's concerns around cljs-ajax moving backends too. This PR only captures the return value of the original function used to perform the ajax request, and then dispatches that value to the handler. I might have missed something in the initial objection that could have been obvious to someone with deeper knowledge of the differences between Closure and XmlHttpRequest, but for this level of abstraction I don't a problem.

**Comment by superstructor** [comment]
Thanks for the feature @kennethkalmer  👍 

`http-fx` is probably going to be superseded at some point in the not too distant future. Exploration of that has already been underway since last year in [http-fx-alpha](https://github.com/day8/re-frame-http-fx-alpha) and [re-frame-fetch-fx](https://github.com/superstructor/re-frame-fetch-fx).

But in the meantime I don't see any disadvantage to merging this improvement and its got a reasonable use case of being able to cancel long running requests.

**Pull request merged**
